/*
 * glyphb.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author  __USER__
 */
public class glyphb extends javax.swing.JFrame {

	/** Creates new form glyphb */
	public glyphb() {
		initComponents();
		this.setTitle("Ôª´´");
		Image image = Toolkit.getDefaultToolkit().getImage("img1/7.png");
		setIconImage(image);
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton20 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jButton16 = new javax.swing.JButton();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();

		jButton20.setBackground(new java.awt.Color(204, 204, 204));
		jButton20.setForeground(new java.awt.Color(255, 255, 255));
		jButton20.setText("\u7ba1\u7406\u5e7f\u544a");
		jButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton20ActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton9.setBackground(new java.awt.Color(204, 204, 204));
		jButton9.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jButton9.setForeground(new java.awt.Color(255, 255, 255));
		jButton9.setText("<");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setBackground(new java.awt.Color(204, 204, 204));
		jButton10.setForeground(new java.awt.Color(255, 255, 255));
		jButton10.setText("\u6211\u7684\u4e3b\u9875");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setBackground(new java.awt.Color(204, 204, 204));
		jButton11.setForeground(new java.awt.Color(255, 255, 255));
		jButton11.setText("\u5546\u5e97");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setBackground(new java.awt.Color(204, 204, 204));
		jButton12.setForeground(new java.awt.Color(255, 255, 255));
		jButton12.setText("\u7ba1\u7406\u7528\u6237");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jButton17.setBackground(new java.awt.Color(204, 204, 204));
		jButton17.setForeground(new java.awt.Color(255, 255, 255));
		jButton17.setText("\u7ba1\u7406\u5546\u5bb6");
		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});

		jButton18.setBackground(new java.awt.Color(204, 204, 204));
		jButton18.setForeground(new java.awt.Color(255, 255, 255));
		jButton18.setText("\u7ba1\u7406\u6e38\u620f");
		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});

		jButton19.setBackground(new java.awt.Color(204, 204, 204));
		jButton19.setForeground(new java.awt.Color(255, 255, 255));
		jButton19.setText("\u516c\u544a/\u5e7f\u544a");
		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});

		jButton21.setBackground(new java.awt.Color(204, 204, 204));
		jButton21.setForeground(new java.awt.Color(255, 255, 255));
		jButton21.setText("\u6ce8\u9500");
		jButton21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton21ActionPerformed(evt);
			}
		});

		jButton15.setBackground(new java.awt.Color(204, 204, 204));
		jButton15.setForeground(new java.awt.Color(255, 255, 255));
		jButton15.setText("\u7cbe\u9009");
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});

		jButton13.setBackground(new java.awt.Color(204, 204, 204));
		jButton13.setForeground(new java.awt.Color(255, 255, 255));
		jButton13.setText("\u6392\u884c\u699c");

		jButton14.setBackground(new java.awt.Color(204, 204, 204));
		jButton14.setForeground(new java.awt.Color(255, 255, 255));
		jButton14.setText("\u6240\u6709\u6e38\u620f");
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});

		jTextField1.setForeground(new java.awt.Color(204, 204, 204));
		jTextField1.setText("\u641c\u7d22\u6e38\u620f");

		jButton16.setBackground(new java.awt.Color(204, 204, 204));
		jButton16.setForeground(new java.awt.Color(255, 255, 255));
		jButton16.setText("ok");
		jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton16MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jButton16MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jButton16MouseExited(evt);
			}
		});
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});

		jTable3.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable3.setRowHeight(50);
		jScrollPane5.setViewportView(jTable3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(jButton9)
										.addGap(28, 28, 28)
										.addComponent(jButton10)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton12)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton17)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton18)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton19)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												103, Short.MAX_VALUE)
										.addComponent(
												jButton21,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												76,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jButton15,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												74,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton13)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton14)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												272, Short.MAX_VALUE)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												145,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton16).addGap(94, 94,
												94)).addGroup(
								layout.createSequentialGroup().addGap(70, 70,
										70).addComponent(jScrollPane5,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										635,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(126, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton9)
														.addComponent(jButton10)
														.addComponent(jButton11)
														.addComponent(jButton12)
														.addComponent(jButton17)
														.addComponent(jButton18)
														.addComponent(jButton19)
														.addComponent(jButton21))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton13)
														.addComponent(jButton14)
														.addComponent(jButton15)
														.addComponent(jButton16)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												36, Short.MAX_VALUE)
										.addComponent(
												jScrollPane5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		new glymianview().setVisible(true);
		this.dispose();
	}

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		//new AdministratorInterface().setVisible(true);
		this.dispose();
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		new glymianview().setVisible(true);
		this.dispose();
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		new glyzy2().setVisible(true);
		this.dispose();
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton16MouseExited(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI("http://baidu.com/");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton16MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		new glysyyx().setVisible(true);
		this.dispose();
	}

	private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
		new view2().setVisible(true);
		this.dispose();
	}

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdministratorInterface2().setVisible(true);
		this.dispose();
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdminitratorInterface5().setVisible(true);
		this.dispose();
	}

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdministratorInterface4().setVisible(true);
		this.dispose();
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdministratorInterface3().setVisible(true);
		this.dispose();
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new glyphb().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton9;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTable jTable3;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}