/*
 * glyyxjs.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.UnknownHostException;

import javax.swing.JOptionPane;

import Server.Client;

import model.manager;

/**
 *
 * @author  __USER__
 */
public class glyyxjs extends javax.swing.JFrame {
	private static manager m;
	/** Creates new form glyyxjs */
	public glyyxjs() {
		initComponents();
		this.m= m;
		this.setLocationRelativeTo(null);
		Image image = Toolkit.getDefaultToolkit().getImage("img1/7.png");
		setIconImage(image);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jButton6 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jTextField6 = new javax.swing.JTextField();
		jButton7 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/绝地求生.jpg"))); // NOI18N

		jLabel1.setText("\u6e38\u620f\u8be6\u60c5");

		jTextArea4.setColumns(20);
		jTextArea4.setRows(5);
		jScrollPane4.setViewportView(jTextArea4);

		jButton6.setText("\u6e38\u620f\u89c6\u9891\u4ecb\u7ecd");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jTextArea3
				.setText("\u7edd\u4e16\u6c42\u751f\uff1a\n\u300a\u7edd\u5730\u6c42\u751f\u300b\u662f\u5927\u9003\u6740\u7c7b\u591a\u4eba\u5c04\u51fb\u6e38\u620f\u300aPLAYERUNKNOWN");
		jScrollPane3.setViewportView(jTextArea3);

		jTextField6.setText("[\u7edd\u5730\u6c42\u751f]");
		jTextField6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField6ActionPerformed(evt);
			}
		});

		jButton7.setText("\u53d1\u9001");
//		jButton7.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton7ActionPerformed(evt);
//			}
//		});

		jButton5.setBackground(new java.awt.Color(204, 204, 204));
		jButton5.setForeground(new java.awt.Color(255, 255, 255));
		jButton5.setText("\u7acb\u5373\u8d2d\u4e70");
		jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton5MouseClicked(evt);
			}
		});
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel7.setText("\u4ef7\u683c\uff1a");

		jTextField5.setText("98");
		jTextField5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});

		jButton9.setBackground(new java.awt.Color(204, 204, 204));
		jButton9.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jButton9.setForeground(new java.awt.Color(255, 255, 255));
		jButton9.setText("<");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setBackground(new java.awt.Color(204, 204, 204));
		jButton10.setForeground(new java.awt.Color(255, 255, 255));
		jButton10.setText("\u6211\u7684\u4e3b\u9875");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setBackground(new java.awt.Color(204, 204, 204));
		jButton11.setForeground(new java.awt.Color(255, 255, 255));
		jButton11.setText("\u5546\u5e97");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setBackground(new java.awt.Color(204, 204, 204));
		jButton12.setForeground(new java.awt.Color(255, 255, 255));
		jButton12.setText("\u7ba1\u7406\u7528\u6237");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jButton17.setBackground(new java.awt.Color(204, 204, 204));
		jButton17.setForeground(new java.awt.Color(255, 255, 255));
		jButton17.setText("\u7ba1\u7406\u5546\u5bb6");
		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});

		jButton18.setBackground(new java.awt.Color(204, 204, 204));
		jButton18.setForeground(new java.awt.Color(255, 255, 255));
		jButton18.setText("\u7ba1\u7406\u6e38\u620f");
		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});

		jButton19.setBackground(new java.awt.Color(204, 204, 204));
		jButton19.setForeground(new java.awt.Color(255, 255, 255));
		jButton19.setText("\u516c\u544a");
		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});

		jButton20.setBackground(new java.awt.Color(204, 204, 204));
		jButton20.setForeground(new java.awt.Color(255, 255, 255));
		jButton20.setText("\u7ba1\u7406\u5e7f\u544a");
		jButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton20ActionPerformed(evt);
			}
		});

		jButton21.setBackground(new java.awt.Color(204, 204, 204));
		jButton21.setForeground(new java.awt.Color(255, 255, 255));
		jButton21.setText("\u6ce8\u9500");
		jButton21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton21ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(jButton9)
										.addGap(28, 28, 28)
										.addComponent(jButton10)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton12)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton17)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton18)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton19)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton20)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												39, Short.MAX_VALUE)
										.addComponent(
												jButton21,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												76,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout
														.createSequentialGroup()
														.addGap(31, 31, 31)
														.addComponent(jLabel6)
														.addGap(36, 36, 36)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel1)
																						.addGap(
																								378,
																								378,
																								378))
																		.addComponent(
																				jScrollPane4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				492,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton6,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				492,
																				Short.MAX_VALUE)
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				492,
																				Short.MAX_VALUE)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								420,
																								Short.MAX_VALUE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jButton7)))
														.addGap(22, 22, 22)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jButton5,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				148,
																				Short.MAX_VALUE)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel7)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								97,
																								Short.MAX_VALUE)))
														.addGap(32, 32, 32))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton9)
														.addComponent(jButton10)
														.addComponent(jButton11)
														.addComponent(jButton12)
														.addComponent(jButton17)
														.addComponent(jButton18)
														.addComponent(jButton19)
														.addComponent(jButton20)
														.addComponent(jButton21))
										.addContainerGap(497, Short.MAX_VALUE))
						.addGroup(
								layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout
														.createSequentialGroup()
														.addGap(40, 40, 40)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel1)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jButton6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								169,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addGap(
																								86,
																								86,
																								86)
																						.addComponent(
																								jLabel6)
																						.addGap(
																								29,
																								29,
																								29)))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addGap(
																								23,
																								23,
																								23)
																						.addComponent(
																								jScrollPane3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								57,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addGap(
																								34,
																								34,
																								34)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel7)
																										.addComponent(
																												jTextField5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jScrollPane4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton5))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jButton7)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addContainerGap(40,
																Short.MAX_VALUE))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
		new view2().setVisible(true);
		this.dispose();
	}

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdministratorInterface2().setVisible(true);
		this.dispose();
	}

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		//new AdministratorInterface().setVisible(true);
		this.dispose();
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdminitratorInterface5().setVisible(true);
		this.dispose();
	}

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdministratorInterface4().setVisible(true);
		this.dispose();
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdministratorInterface3().setVisible(true);
		this.dispose();
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		new glymianview().setVisible(true);
		this.dispose();
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		new glyzy2().setVisible(true);
		this.dispose();
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {
		this.jButton5.setVisible(false);
		JOptionPane.showMessageDialog(null, "购买成功");
		this.jTextField5.setVisible(false);
		this.jLabel7.setVisible(false);
		URI uri;
		try {
			uri = new URI(
					"http://guanjia.qq.com/act/sem/201711ak/?ADTAG=360_sem_jdqs");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

//	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
//		Client c;
//		try {
//			c = new Client();
//			c.usercomment(u, this.jTextField6.getText());
//			load();
//		} catch (UnknownHostException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//	}

	private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		VideoPlayDemo.Run("C:\\Users\\林十三\\Desktop\\元创游戏平台资料\\绝地求生官方宣传片");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new glyyxjs().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

}