/*
 * 登录.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.UnknownHostException;
import java.util.Scanner;

import javax.swing.JOptionPane;

import model.user;
import Server.Client;

/**
 *
 * @author  __USER__
 */
public class login extends javax.swing.JFrame {

	/** Creates new form 登录 */
	public login() {
		initComponents();
		this.jPasswordField3.setEchoChar('\0');
		this.jPasswordField3.setText("密码");
		this.setTitle("元创");
		this.setLocationRelativeTo(null);
		Image image = Toolkit.getDefaultToolkit().getImage("img1/7.png");
		setIconImage(image);
		this.记住密码();
	}

	private void 记住密码() {

		File f = new File("user.txt");
		System.out.println(f.exists());
		if (f.exists()) {
			try {
				Scanner sc = new Scanner(f);
				String name = sc.nextLine();
				String pw = sc.nextLine();
				this.jTextField6.setText(name);
				this.jPasswordField3.setText(pw);
				this.jCheckBox3.setSelected(true);

			} catch (FileNotFoundException e) {
				// TODO: handle exception
				e.printStackTrace();
			}

		}
	}

	private String encry(String info) {
		char[] c = info.toCharArray();
		String out = "";
		for (int i = 0; i < c.length; i++) {
			out += (c[i] + 5);
		}
		return out;
	}

	private void add记住() {
		File f = new File("user.txt");
		PrintWriter pw;
		try {
			pw = new PrintWriter(f);
			pw.println(this.jTextField6.getText());
			pw.println((this.jPasswordField3.getText()));
			pw.flush();

		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField2 = new javax.swing.JTextField();
		jTextField1 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jCheckBox1 = new javax.swing.JCheckBox();
		jPasswordField1 = new javax.swing.JPasswordField();
		jTextField3 = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jCheckBox2 = new javax.swing.JCheckBox();
		jPasswordField2 = new javax.swing.JPasswordField();
		jTextField5 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jCheckBox3 = new javax.swing.JCheckBox();
		jPasswordField3 = new javax.swing.JPasswordField();
		jTextField6 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();

		jTextField1.setText("\u8d26\u53f7");

		jTextField4.setText("\u4fdd\u5b58\u5bc6\u7801");

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 48));
		jLabel1.setText("\u5143\u521b");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 48));
		jLabel2.setText("\u5143\u521b");

		jButton1.setBackground(new java.awt.Color(204, 204, 204));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jCheckBox1.setText("\u4fdd\u5b58\u5bc6\u7801");

		jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
		jPasswordField1.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());
		jPasswordField1.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jPasswordField1KeyTyped(evt);
			}
		});

		jTextField3.setForeground(new java.awt.Color(204, 204, 204));
		jTextField3.setText("\u7528\u6237\u8d26\u53f7");
		jTextField3.setAutoscrolls(false);
		jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jTextField3.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField3KeyTyped(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(98, 98, 98)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jCheckBox1,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jPasswordField1,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				160,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(136, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addComponent(jLabel2)
										.addGap(56, 56, 56)
										.addComponent(
												jTextField3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPasswordField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBox1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(62, Short.MAX_VALUE)));

		jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 48));
		jLabel4.setText("\u5143\u521b");

		jButton2.setBackground(new java.awt.Color(204, 204, 204));
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("\u767b\u5f55");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jCheckBox2.setText("\u4fdd\u5b58\u5bc6\u7801");

		jPasswordField2.setForeground(new java.awt.Color(204, 204, 204));
		jPasswordField2.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());
		jPasswordField2.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jPasswordField2KeyTyped(evt);
			}
		});

		jTextField5.setForeground(new java.awt.Color(204, 204, 204));
		jTextField5.setText("\u7528\u6237\u8d26\u53f7");
		jTextField5.setAutoscrolls(false);
		jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jTextField5.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField5KeyTyped(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(98, 98, 98)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jCheckBox2,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jPasswordField2,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jTextField5,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				160,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(136, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addComponent(jLabel4)
										.addGap(56, 56, 56)
										.addComponent(
												jTextField5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPasswordField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBox2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(62, Short.MAX_VALUE)));

		setBackground(java.awt.Color.black);

		jPanel4.setBackground(new java.awt.Color(0, 0, 0));
		jPanel4.setForeground(new java.awt.Color(51, 51, 51));

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 48));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u5143\u521b");

		jButton3.setBackground(new java.awt.Color(204, 204, 204));
		jButton3.setForeground(new java.awt.Color(255, 255, 255));
		jButton3.setText("\u767b\u5f55");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jCheckBox3.setText("\u4fdd\u5b58\u5bc6\u7801");

		jPasswordField3.setForeground(new java.awt.Color(204, 204, 204));
		jPasswordField3.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());
		jPasswordField3.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField3ActionPerformed(evt);
			}
		});
		jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jPasswordField3KeyTyped(evt);
			}
		});

		jTextField6.setForeground(new java.awt.Color(204, 204, 204));
		jTextField6.setText("\u7528\u6237\u8d26\u53f7");
		jTextField6.setAutoscrolls(false);
		jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jTextField6.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField6KeyTyped(evt);
			}
		});

		jButton4.setBackground(new java.awt.Color(204, 204, 204));
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("\u6ce8\u518c");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				237,
																				237,
																				237)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jCheckBox3,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jPasswordField3,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								160,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton4,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				265,
																				265,
																				265)
																		.addComponent(
																				jLabel5)))
										.addContainerGap(260, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(130, 130, 130)
										.addComponent(jLabel5)
										.addGap(45, 45, 45)
										.addComponent(
												jTextField6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPasswordField3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBox3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(
												jButton4).addContainerGap(105,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(642, 642, 642)
						.addComponent(jLabel3).addContainerGap(
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addComponent(jPanel4,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		new BuildUser().setVisible(true);
		this.dispose();
	}

	private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {
		if (this.jTextField6.getText().equals("用户账号"))

			this.jTextField6.setText("");
	}

	private void jPasswordField3KeyTyped(java.awt.event.KeyEvent evt) {
		if (this.jPasswordField1.getText().equals("密码")) {
			this.jPasswordField1.setText("");
			this.jPasswordField1.setEchoChar('*');
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.jCheckBox3.isSelected())
			add记住();
		else {
			File f = new File("C:\\Users\\林十三\\Desktop\\游戏平台\\user.txt");
			System.out.println(f.exists());
			f.delete();
		}
		try {
			Client c = new Client();
			user u = c.userLogin(this.jTextField6.getText(),
					this.jPasswordField3.getText());
			if (u == null)
				JOptionPane.showMessageDialog(this, "登录失败");
			else {

				new GameIntroduce(u).setVisible(true);
				new UserMainInterface().setVisible(true);
				this.dispose();
			}

		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
	}

	private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.jCheckBox3.isSelected())
			add记住();
		else {
			File f = new File("C:\\Users\\林十三\\Desktop\\游戏平台\\user.txt");
			System.out.println(f.exists());
			f.delete();
		}
		try {
			Client c = new Client();
			user u = c.userLogin(this.jTextField6.getText(),
					this.jPasswordField3.getText());
			if (u == null)
				JOptionPane.showMessageDialog(this, "登录失败");
			else {
				new UserMainInterface().setVisible(true);
				new GameIntroduce(u).setVisible(true);
				this.dispose();
			}

		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {
		if (this.jPasswordField1.getText().equals("密码")) {
			this.jPasswordField1.setText("");
			this.jPasswordField1.setEchoChar('*');
		}
	}

	private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {
		if (this.jTextField3.getText().equals("用户账号"))

			this.jTextField3.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

}