/*
 * sjsd.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.UnknownHostException;

import javax.swing.ImageIcon;

import Server.Client;

/**
 *
 * @author  __USER__
 */
public class sjsd extends javax.swing.JFrame implements Runnable {

	/** Creates new form sjsd */
	public sjsd() {
		initComponents();
		this.setLocationRelativeTo(null);
		Image image = Toolkit.getDefaultToolkit().getImage("img1/7.png");
		setIconImage(image);
		this.setTitle("Ôª´´");
		Thread t = new Thread(this);
		t.start();
		load();
		loads();
	}

	private void loads() {
		try {
			Client c = new Client();
			String s = c.viewannouncement();
			this.jTextField4.setText(s);
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void load() {
		try {
			Client c = new Client();
			String s = c.advertisement();
			this.jTextArea6.setText(s);
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void lunbo() {
		for (int i = 1; i <= 5; i++) {
			this.jLabel1.setIcon(new ImageIcon("img/" + i + ".jpg"));
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if (i == 5)
				i = 1;
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField2 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jButton8 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jButton22 = new javax.swing.JButton();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton25 = new javax.swing.JButton();
		jButton26 = new javax.swing.JButton();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTextArea6 = new javax.swing.JTextArea();
		jTextField4 = new javax.swing.JTextField();

		jTextField2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextField3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setBackground(new java.awt.Color(204, 204, 204));
		jButton1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("<");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(204, 204, 204));
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("\u6211\u7684\u4e3b\u9875");

		jButton3.setBackground(new java.awt.Color(204, 204, 204));
		jButton3.setForeground(new java.awt.Color(255, 255, 255));
		jButton3.setText("\u5546\u5e97");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setBackground(new java.awt.Color(204, 204, 204));
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("\u7ba1\u7406\u6e38\u620f");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton11.setBackground(new java.awt.Color(204, 204, 204));
		jButton11.setForeground(new java.awt.Color(255, 255, 255));
		jButton11.setText("\u6ce8\u9500");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton16.setBackground(new java.awt.Color(204, 204, 204));
		jButton16.setForeground(new java.awt.Color(255, 255, 255));
		jButton16.setText("\u7cbe\u9009");

		jButton7.setBackground(new java.awt.Color(204, 204, 204));
		jButton7.setForeground(new java.awt.Color(255, 255, 255));
		jButton7.setText("\u6392\u884c\u699c");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton13.setBackground(new java.awt.Color(204, 204, 204));
		jButton13.setForeground(new java.awt.Color(255, 255, 255));
		jButton13.setText("\u6240\u6709\u6e38\u620f");
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});

		jTextField1.setForeground(new java.awt.Color(204, 204, 204));
		jTextField1.setText("\u641c\u7d22\u6e38\u620f");

		jButton8.setBackground(new java.awt.Color(204, 204, 204));
		jButton8.setForeground(new java.awt.Color(255, 255, 255));
		jButton8.setText("ok");
		jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton8MouseClicked(evt);
			}
		});

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/gg1_..jpg"))); // NOI18N

		jLabel2.setText("\u70ed\u95e8\u6e38\u620f");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/ÂÖ²¥Í¼1.jpg"))); // NOI18N

		jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/Ó¢ÐÛÁªÃË.jpg"))); // NOI18N
		jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton22MouseClicked(evt);
			}
		});

		jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/±¤ÀÝÖ®Ò¹.jpg"))); // NOI18N
		jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton23MouseClicked(evt);
			}
		});

		jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/¾øµØÇóÉú.jpg"))); // NOI18N
		jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton24MouseClicked(evt);
			}
		});
		jButton24.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton24ActionPerformed(evt);
			}
		});

		jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/ÃÎ»ÃÎ÷ÓÎ.jpg"))); // NOI18N
		jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton25MouseClicked(evt);
			}
		});
		jButton25.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton25ActionPerformed(evt);
			}
		});

		jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/×ï¶ñ¶¼ÊÐ.jpg"))); // NOI18N
		jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton26MouseClicked(evt);
			}
		});

		jTextArea6.setColumns(20);
		jTextArea6.setFont(new java.awt.Font("Monospaced", 0, 36));
		jTextArea6.setForeground(new java.awt.Color(255, 51, 255));
		jTextArea6.setRows(5);
		jScrollPane6.setViewportView(jTextArea6);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(jButton1)
										.addGap(146, 146, 146)
										.addComponent(jButton2)
										.addGap(12, 12, 12)
										.addComponent(
												jButton3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												77,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jButton4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												191, Short.MAX_VALUE)
										.addComponent(jButton11))
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jButton16,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												74,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton13)
										.addGap(211, 211, 211)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												145,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton8).addGap(58, 58,
												58))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																638,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				0,
																				0,
																				Short.MAX_VALUE)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton22,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								69,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								58,
																								58,
																								58)
																						.addComponent(
																								jButton23,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								68,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								63,
																								63,
																								63)
																						.addComponent(
																								jButton24,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								67,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								61,
																								61,
																								61)
																						.addComponent(
																								jButton25,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								71,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								56,
																								56,
																								56)
																						.addComponent(
																								jButton26,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								70,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				jScrollPane6,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				587,
																				Short.MAX_VALUE)))
										.addContainerGap(33, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2)
														.addComponent(jButton3)
														.addComponent(jButton4)
														.addComponent(jButton11))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				7,
																				7,
																				7)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton7)
																						.addComponent(
																								jButton13)
																						.addComponent(
																								jButton16)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton8))))
										.addGap(18, 18, 18)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton23,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																99,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton22,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																98,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton24,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																99,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jButton26,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				98,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton25,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				97,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jTextField4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel5)
										.addGap(33, 33, 33)
										.addComponent(
												jScrollPane6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												130,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(39, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		new MerchantInterface().setVisible(true);
		this.dispose();
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI("https://dl.pconline.com.cn/download/84973-1.html");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI(
					"http://xy.skysgame.com/index.htm?fromid=xy306jpchx375");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {
		//new GameIntroduce().setVisible(true);
	}

	private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI("https://lol.qq.com/");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI("http://fn.qq.com/web201803/main.shtml");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI("https://lol.qq.com/");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {
		URI uri;
		try {
			uri = new URI("https://www.baidu.com/");
			Desktop dtp = Desktop.getDesktop();
			if (Desktop.isDesktopSupported()
					&& dtp.isSupported(Desktop.Action.BROWSE)) {
				try {

					dtp.browse(uri);

				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		} catch (URISyntaxException e1) {

			e1.printStackTrace();
		}
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		new sjsyyx().setVisible(true);
		this.dispose();
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		new sjphb().setVisible(true);
		this.dispose();
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		new view2().setVisible(true);
		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		new view2().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new sjsd().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea6;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;

	// End of variables declaration//GEN-END:variables
	@Override
	public void run() {
		// TODO Auto-generated method stub

		lunbo();

	}

}